version: '3'

services:
  
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

  master:
    build: master
    volumes:
      - ./master:/app
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - PYTHONUNBUFFERED=1

  orchestrator:
    build: orchestrator
    volumes:
      - ./orchestrator:/app
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:5000

  zoo1:
    image: 'zookeeper'
    restart: on-failure
    hostname: zoo1
    ports: 
      - '2181:2181'
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888;2181
    
